#include "p16f877a.inc"

; CONFIG
; __config 0x3FFF
 __CONFIG _FOSC_EXTRC & _WDTE_ON & _PWRTE_OFF & _BOREN_ON & _LVP_ON & _CPD_OFF & _WRT_OFF & _CP_OFF
STATUS equ 03h
 RP0 equ 05
 RP1 equ 06
 
 PORTA equ 05h
 TRISA equ 85h
 
 COUNTER1 equ 20h
 COUNTER2 equ 21h
 
org 00h
 
    clrw
    BCF STATUS, RP0
    BCF STATUS, RP1
    CLRF PORTA
    BSF STATUS, RP0
    MOVLW 0x00 
    MOVWF TRISA
    BCF STATUS, RP0
 START MOVLW 0x04
    MOVWF PORTA 
    MOVLW 0xff
    MOVWF COUNTER1  
LOOP1  MOVLW 0xff
    MOVWF COUNTER2
LOOP3 DECFSZ COUNTER2,1
    GOTO LOOP3
    DECFSZ COUNTER1,1 
    GOTO LOOP1 
    MOVLW 0x02
    MOVWF PORTA
    MOVLW 0xC8
    MOVWF COUNTER1    
LOOP4  MOVLW 0xff
    MOVWF COUNTER2
LOOP5 DECFSZ COUNTER2,1
    GOTO LOOP5
    DECFSZ COUNTER1,1
    GOTO LOOP4
    MOVLW 0x01
    MOVWF PORTA
    MOVLW 0xff
    MOVWF COUNTER1       
LOOP2 MOVLW 0xff
    MOVWF COUNTER2 
LOOP6 DECFSZ COUNTER2,1
    GOTO LOOP6
    DECFSZ COUNTER1,1
    GOTO LOOP2   
    GOTO START
	 
END



